<?php

namespace Lch\MenuBundle\Repository;

use Lch\MenuBundle\Entity\Menu;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForValidator(Menu $menu){
        $qb = $this->createQueryBuilder('m');
        $qb->andWhere('m.location = :location')
            ->andWhere('m.language = :language')
            ->setParameter('location', $menu->getLocation())
            ->setParameter('language', $menu->getLanguage());

        if ($menu->getId() !== null) {
            $qb->andWhere('m.id != :id')->setParameter('id', $menu->getId());
        } else {
            $qb->andWhere($qb->expr()->isNotNull("m.id"));
        }

        return $qb->getQuery()->getResult();
    }
}
